### ISSUE TITLE
mesh_masks/lips.obj  is missed in the project

### ISSUE THREAD

**Issue by yydxlv** [Zielon/INSTA-pytorch#1]
Hi，

Thanks for your excellent work., I'm interested in the amazing results. However,  i found sth was missed in the code when i run the project.  In insta/masks.py,  '/home/wzielonka/CLionProjects/real-time-avatar/mesh_masks/lips.obj' was not included,  can you fix it, thank you very much!

**Comment by Zielon** [comment]
Hello, I have already added it.
