### ISSUE TITLE
ModuleNotFoundError: No module named 'bvh_distance_queries_cuda'

### ISSUE THREAD

**Issue by Lxiangyue** [Zielon/INSTA-pytorch#17]
Hi Zielon, thank you for your amazing work! 

I wanted to ask if there is a missing module in the repository. When I run the INSTA-pytorch code, I receive an error message stating "No module named 'bvh_distance_queries_cuda'". I have searched both your repository and the BVH repository, but I cannot find any module with that name. Could you please advise me on how to resolve this issue?

Looking forward to your reply!

**Comment by Lxiangyue** [comment]
I fixed it by: sudo cp /usr/local/lib/python3.10/dist-packages/torch/lib/* /usr/lib/

**Comment by Larry-u** [comment]
@Lxiangyue May I ask what is your GPU type and CUDA version?
