### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by ulucsahin** [Zielon/INSTA-pytorch#2]
I have 32 GB of RAM and Tesla T4 with 16 GB VRAM.

I see that 24GB of VRAM is required. Disabling `-O` and just using `--fp16 --cuda_ray` seem to reduce VRAM requirements.

However, I am running out of regular memory during data preparation at the start of third epoch.

What is the memory requirements with this setting?

**Comment by Zielon** [comment]
There is a cache in data loader https://github.com/Zielon/INSTA-pytorch/blob/master/insta/provider.py#L148. You could disable it of your RAM is less than 32 GB.

**Comment by ulucsahin** [comment]
It is 32 GB. Memory usage increases every epoch and fails on third epoch.

I will try disabling in any case.
